name: Prepare Extension Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  VITE_APP_BASE_URL: 'https://app.getsavory.co'

jobs:
  build:
    permissions:
      contents: write # for softprops/action-gh-release to create GitHub release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm install
      - run: npm run build:ext
      - name: Create zip file
        run: zip -r "$GITHUB_REF_NAME.zip" dist
      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          draft: true
          files: '*.zip'
